# Generated by Django 4.0.5 on 2022-07-03 14:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
    ]
