# Generated by Django 4.0.5 on 2022-07-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_lesson_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.lesson'),
        ),
    ]
