# Generated by Django 4.0.5 on 2022-07-03 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_homework_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='homework',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 14, 44, 16, 243502, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
