# Generated by Django 4.0.5 on 2022-07-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_homework_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='attachment',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='todo.lesson'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='homework',
            name='reminder',
            field=models.DateTimeField(blank=True, verbose_name='Reminder'),
        ),
    ]
