# Generated by Django 4.0.5 on 2022-07-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_homework_attachment_alter_homework_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='attachment',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reminder'),
        ),
    ]
